param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Assert-FolderExists {
    <#
    .SYNOPSIS
    Ensures a folder exists.

    Args:
        path (string): Folder path.

    Returns:
        None
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -Path $Path -PathType Container)) {
        throw "Folder not found: $Path"
    }
}

function Ensure-Folder {
    <#
    .SYNOPSIS
    Creates a folder if it does not exist.

    Args:
        path (string): Folder path.

    Returns:
        string: Folder path.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -Path $Path -PathType Container)) {
        New-Item -Path $Path -ItemType Directory | Out-Null
    }

    return $Path
}

function Write-TextFileUtf8NoBom {
    <#
    .SYNOPSIS
    Writes a UTF-8 (no BOM) text file, creating parent folders as needed.
    Accepts a string, string array, or anything enumerable.

    Args:
        path (string): Output file path.
        lines (object): Lines (string or string[]) to write.

    Returns:
        None
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [AllowNull()]
        [object]$Lines
    )

    $parent = Split-Path -Path $Path -Parent
    if ($parent -and -not (Test-Path -Path $parent -PathType Container)) {
        New-Item -Path $parent -ItemType Directory | Out-Null
    }

    $line_array = @()
    if ($null -eq $Lines) {
        $line_array = @()
    }
    elseif ($Lines -is [string]) {
        $line_array = @($Lines)
    }
    else {
        # Force enumeration into an array, even if it's a single item.
        $line_array = @($Lines)
    }

    $content = $line_array -join "`r`n"
    $utf8_no_bom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $content, $utf8_no_bom)

    Write-Host "✅ Wrote: $Path"
}


function Convert-LuaTreeToUtf8NoBom {
    <#
    .SYNOPSIS
    Converts all .lua files under a folder to UTF-8 without BOM.

    Args:
        root (string): Root folder.

    Returns:
        int: Count converted.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$Root
    )

    $count = 0
    $utf8_no_bom = New-Object System.Text.UTF8Encoding($false)

    Get-ChildItem -Path $Root -Recurse -File -Filter "*.lua" | ForEach-Object {
        $p = $_.FullName
        $raw = Get-Content -Path $p -Raw

        if ($raw.Length -gt 0 -and $raw[0] -eq [char]0xFEFF) {
            $raw = $raw.Substring(1)
        }

        [System.IO.File]::WriteAllText($p, $raw, $utf8_no_bom)
        $count += 1
    }

    return $count
}

function Main {
    <#
    .SYNOPSIS
    Writes a Rojo-friendly NecroSnake “one-shot logic” implementation into
    src/server/Services and updates Main.server.lua. No runtime Source edits.

    Args:
        None

    Returns:
        None
    #>
    Assert-FolderExists -Path $ProjectRoot

    $src_root = Join-Path $ProjectRoot "src"
    Assert-FolderExists -Path $src_root

    $server_root = Ensure-Folder -Path (Join-Path $src_root "server")
    $services_dir = Ensure-Folder -Path (Join-Path $server_root "Services")

    # -----------------------------
    # GameConfig.lua
    # -----------------------------
    $game_config = @(
        "local GameConfig = {}",
        "",
        "GameConfig.Debug = {",
        "    Enabled = true,",
        "    AiEverySeconds = 1.25,",
        "    CombatEverySeconds = 0.35,",
        "    SpawnEverySeconds = 2.0,",
        "}",
        "",
        "GameConfig.World = {",
        "    WorldName = ""NecromancerMVP_World"",",
        "    ArenaName = ""Arena"",",
        "    UnitsName = ""Units"",",
        "    LeadersName = ""Leaders"",",
        "}",
        "",
        "GameConfig.Arena = {",
        "    Center = Vector3.new(0, 0, 0),",
        "    HalfSize = Vector3.new(140, 0, 140),",
        "    GroundY = 1,",
        "}",
        "",
        "GameConfig.Visibility = {",
        "    BillboardMaxDistance = 90,",
        "}",
        "",
        "GameConfig.Formation = {",
        "    GoldenAngle = 137.5 * (math.pi / 180),",
        "    InnerCapacity = 10,",
        "    InnerSpacing = 3.2,",
        "    OuterSpacing = 5.0,",
        "    OuterRadiusBoost = 16,",
        "}",
        "",
        "GameConfig.Units = {",
        "    WeakSkeleton = { Health = 20, Damage = 3, Size = 2.0, Mass = 0.8 },",
        "    Skeleton = { Health = 35, Damage = 5, Size = 2.2, Mass = 1.0 },",
        "    ZombieBrute = { Health = 150, Damage = 15, Size = 3.4, Mass = 5.0 },",
        "    DarkKnight = { Health = 500, Damage = 40, Size = 4.6, Mass = 15.0 },",
        "}",
        "",
        "GameConfig.Colors = {",
        "    PlayerUnit = Color3.fromRGB(80, 170, 255),",
        "    WanderUnit = Color3.fromRGB(120, 220, 120),",
        "    NamedUnit = Color3.fromRGB(210, 80, 255),",
        "    NamedLeader = Color3.fromRGB(230, 60, 60),",
        "    PlayerLeader = Color3.fromRGB(245, 245, 245),",
        "}",
        "",
        "GameConfig.Player = {",
        "    BaseHealth = 120,",
        "    BaseDamage = 12,",
        "    StartCount = 8,",
        "    StartType = ""ZombieBrute"",",
        "}",
        "",
        "GameConfig.Movement = {",
        "    UnitMaxVelocity = 28,",
        "    UnitResponsiveness = 10,",
        "    UnitMaxForce = 35000,",
        "    LeaderMaxVelocity = 13,",
        "    LeaderResponsiveness = 4.2,",
        "    LeaderMaxForce = 30000,",
        "    TargetUpdateMinSeconds = 0.9,",
        "    TargetUpdateMaxSeconds = 2.0,",
        "}",
        "",
        "GameConfig.AI = {",
        "    SenseRange = 120,",
        "    ChaseStopRange = 14,",
        "    FleeDistance = 80,",
        "    Hysteresis = 1.10,",
        "    WanderJitterStuds = 22,",
        "}",
        "",
        "GameConfig.Combat = {",
        "    AttackRange = 12,",
        "    AttackCooldownSeconds = 0.5,",
        "}",
        "",
        "GameConfig.Raising = {",
        "    BaseChance = 0.35,",
        "    NamedLeaderKillGuaranteedBossRaise = true,",
        "    BossRaiseType = ""DarkKnight"",",
        "}",
        "",
        "GameConfig.Spawn = {",
        "    MaxWanderingGroups = 6,",
        "    MaxNamedArmies = 3,",
        "    WanderingGroupMaxSize = 10,",
        "    NamedSpawnChance = 0.18,",
        "    WanderingSpawnChance = 0.60,",
        "    GroupExpirySeconds = 120,",
        "    NamedExpirySeconds = 180,",
        "}",
        "",
        "GameConfig.WanderingCompositions = {",
        "    { ""WeakSkeleton"", ""WeakSkeleton"" },",
        "    { ""Skeleton"" },",
        "    { ""Skeleton"", ""WeakSkeleton"", ""WeakSkeleton"" },",
        "    { ""Skeleton"", ""Skeleton"" },",
        "    { ""ZombieBrute"" },",
        "    { ""ZombieBrute"", ""WeakSkeleton"", ""WeakSkeleton"" },",
        "    { ""ZombieBrute"", ""Skeleton"", ""WeakSkeleton"" },",
        "    { ""ZombieBrute"", ""Skeleton"", ""Skeleton"" },",
        "    { ""Skeleton"", ""Skeleton"", ""Skeleton"" },",
        "}",
        "",
        "GameConfig.NamedNPCs = {",
        "    { Name = ""Grave Baron"", Army = { { Type = ""ZombieBrute"", Count = 3 }, { Type = ""Skeleton"", Count = 6 } } },",
        "    { Name = ""Bone Patrol"", Army = { { Type = ""Skeleton"", Count = 8 } } },",
        "    { Name = ""Rot Walkers"", Army = { { Type = ""ZombieBrute"", Count = 2 }, { Type = ""WeakSkeleton"", Count = 8 } } },",
        "}",
        "",
        "return GameConfig"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "GameConfig.lua") -Lines $game_config

    # -----------------------------
    # WorldService.lua
    # -----------------------------
    $world_service = @(
        "local WorldService = {}",
        "",
        "local Workspace = game:GetService(""Workspace"")",
        "",
        "local function ensure_folder(parent, name)",
        "    local existing = parent:FindFirstChild(name)",
        "    if existing and existing:IsA(""Folder"") then",
        "        return existing",
        "    end",
        "    if existing then",
        "        existing:Destroy()",
        "    end",
        "    local f = Instance.new(""Folder"")",
        "    f.Name = name",
        "    f.Parent = parent",
        "    return f",
        "end",
        "",
        "function WorldService.EnsureWorld(game_config)",
        "    local world = ensure_folder(Workspace, game_config.World.WorldName)",
        "    world:SetAttribute(""NecroSnake"", true)",
        "",
        "    local arena = ensure_folder(world, game_config.World.ArenaName)",
        "    local units = ensure_folder(world, game_config.World.UnitsName)",
        "    local leaders = ensure_folder(world, game_config.World.LeadersName)",
        "",
        "    arena:SetAttribute(""NecroSnake"", true)",
        "    units:SetAttribute(""NecroSnake"", true)",
        "    leaders:SetAttribute(""NecroSnake"", true)",
        "",
        "    return { World = world, Arena = arena, Units = units, Leaders = leaders }",
        "end",
        "",
        "return WorldService"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "WorldService.lua") -Lines $world_service

    # -----------------------------
    # BoundaryService.lua
    # -----------------------------
    $boundary_service = @(
        "local BoundaryService = {}",
        "",
        "local Workspace = game:GetService(""Workspace"")",
        "",
        "local WALL_THICKNESS = 8",
        "local WALL_HEIGHT = 40",
        "",
        "local function make_wall(name, size, cframe, parent)",
        "    local p = Instance.new(""Part"")",
        "    p.Name = name",
        "    p.Size = size",
        "    p.CFrame = cframe",
        "    p.Anchored = true",
        "    p.CanCollide = true",
        "    p.Transparency = 1",
        "    p.Material = Enum.Material.SmoothPlastic",
        "    p.Parent = parent",
        "    p:SetAttribute(""NecroSnake"", true)",
        "    return p",
        "end",
        "",
        "function BoundaryService.BuildWalls(game_config, arena_folder)",
        "    for _, child in ipairs(arena_folder:GetChildren()) do",
        "        if child:IsA(""BasePart"") and child:GetAttribute(""NecroSnakeWall"") == true then",
        "            child:Destroy()",
        "        end",
        "    end",
        "",
        "    local c = game_config.Arena.Center",
        "    local h = game_config.Arena.HalfSize",
        "    local y = game_config.Arena.GroundY + (WALL_HEIGHT / 2) - 1",
        "",
        "    local wall_parent = arena_folder",
        "",
        "    local size_x = Vector3.new((h.X * 2) + WALL_THICKNESS, WALL_HEIGHT, WALL_THICKNESS)",
        "    local size_z = Vector3.new(WALL_THICKNESS, WALL_HEIGHT, (h.Z * 2) + WALL_THICKNESS)",
        "",
        "    local north = make_wall(""Wall_North"", size_x, CFrame.new(c.X, y, c.Z - h.Z - (WALL_THICKNESS / 2)), wall_parent)",
        "    local south = make_wall(""Wall_South"", size_x, CFrame.new(c.X, y, c.Z + h.Z + (WALL_THICKNESS / 2)), wall_parent)",
        "    local west = make_wall(""Wall_West"", size_z, CFrame.new(c.X - h.X - (WALL_THICKNESS / 2), y, c.Z), wall_parent)",
        "    local east = make_wall(""Wall_East"", size_z, CFrame.new(c.X + h.X + (WALL_THICKNESS / 2), y, c.Z), wall_parent)",
        "",
        "    north:SetAttribute(""NecroSnakeWall"", true)",
        "    south:SetAttribute(""NecroSnakeWall"", true)",
        "    west:SetAttribute(""NecroSnakeWall"", true)",
        "    east:SetAttribute(""NecroSnakeWall"", true)",
        "",
        "    print(string.format(""[BoundaryService] Built invisible walls. HALF_SIZE=%d"", h.X))",
        "end",
        "",
        "function BoundaryService.ClampToArena(game_config, pos)",
        "    local c = game_config.Arena.Center",
        "    local h = game_config.Arena.HalfSize",
        "    local x = math.clamp(pos.X, c.X - h.X, c.X + h.X)",
        "    local z = math.clamp(pos.Z, c.Z - h.Z, c.Z + h.Z)",
        "    return Vector3.new(x, game_config.Arena.GroundY, z)",
        "end",
        "",
        "return BoundaryService"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "BoundaryService.lua") -Lines $boundary_service

    # -----------------------------
    # ModelLibraryService.lua
    # -----------------------------
    $model_library = @(
        "local ModelLibraryService = {}",
        "",
        "local ReplicatedStorage = game:GetService(""ReplicatedStorage"")",
        "",
        "local LIB_FOLDER_NAME = ""ModelLibrary""",
        "",
        "local function get_library()",
        "    local lib = ReplicatedStorage:FindFirstChild(LIB_FOLDER_NAME)",
        "    if lib and lib:IsA(""Folder"") then",
        "        return lib",
        "    end",
        "    lib = Instance.new(""Folder"")",
        "    lib.Name = LIB_FOLDER_NAME",
        "    lib.Parent = ReplicatedStorage",
        "    return lib",
        "end",
        "",
        "local function ensure_primary_part(model)",
        "    if model.PrimaryPart then",
        "        return",
        "    end",
        "    local part = model:FindFirstChildWhichIsA(""BasePart"", true)",
        "    if part then",
        "        model.PrimaryPart = part",
        "    end",
        "end",
        "",
        "local function sanitize_model(model)",
        "    for _, inst in ipairs(model:GetDescendants()) do",
        "        if inst:IsA(""BasePart"") then",
        "            inst.CanCollide = false",
        "            inst.CanTouch = false",
        "            inst.CanQuery = false",
        "            inst.Massless = true",
        "        end",
        "    end",
        "    ensure_primary_part(model)",
        "end",
        "",
        "function ModelLibraryService.Sanitize()",
        "    local lib = get_library()",
        "    local count = 0",
        "    for _, child in ipairs(lib:GetChildren()) do",
        "        if child:IsA(""Model"") then",
        "            sanitize_model(child)",
        "            count += 1",
        "        end",
        "    end",
        "    print(string.format(",
        "        ""[ModelLibraryService] Ready. Models=%d. (Drop models into ReplicatedStorage/ModelLibrary named by unit type.)"",",
        "        count",
        "    ))",
        "end",
        "",
        "function ModelLibraryService.GetTemplate(model_key)",
        "    if typeof(model_key) ~= ""string"" or model_key == """" then",
        "        return nil",
        "    end",
        "    local lib = get_library()",
        "    local m = lib:FindFirstChild(model_key)",
        "    if m and m:IsA(""Model"") then",
        "        return m",
        "    end",
        "    return nil",
        "end",
        "",
        "return ModelLibraryService"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "ModelLibraryService.lua") -Lines $model_library

    # -----------------------------
    # UnitFactoryService.lua
    # -----------------------------
    $unit_factory = @(
        "local UnitFactoryService = {}",
        "",
        "local ModelLibraryService = require(script.Parent.ModelLibraryService)",
        "",
        "local function weld_visual_to_core(core, visual_model)",
        "    if not visual_model.PrimaryPart then",
        "        local pp = visual_model:FindFirstChildWhichIsA(""BasePart"", true)",
        "        if not pp then",
        "            return false",
        "        end",
        "        visual_model.PrimaryPart = pp",
        "    end",
        "",
        "    visual_model:SetPrimaryPartCFrame(core.CFrame)",
        "",
        "    for _, part in ipairs(visual_model:GetDescendants()) do",
        "        if part:IsA(""BasePart"") then",
        "            part.Anchored = false",
        "            part.CanCollide = false",
        "            part.CanTouch = false",
        "            part.CanQuery = false",
        "            part.Massless = true",
        "",
        "            local weld = Instance.new(""WeldConstraint"")",
        "            weld.Part0 = core",
        "            weld.Part1 = part",
        "            weld.Parent = part",
        "        end",
        "    end",
        "",
        "    return true",
        "end",
        "",
        "local function clear_existing_visual(core)",
        "    local existing = core:FindFirstChild(""Visual"")",
        "    if existing then",
        "        existing:Destroy()",
        "    end",
        "end",
        "",
        "function UnitFactoryService.ApplyVisual(core, model_key)",
        "    if not core or not core:IsA(""BasePart"") then",
        "        return",
        "    end",
        "",
        "    clear_existing_visual(core)",
        "",
        "    local template = ModelLibraryService.GetTemplate(model_key)",
        "    if not template then",
        "        core.Transparency = 0",
        "        return",
        "    end",
        "",
        "    local visual = template:Clone()",
        "    visual.Name = ""Visual""",
        "    visual.Parent = core",
        "",
        "    local ok = weld_visual_to_core(core, visual)",
        "    if ok then",
        "        core.Transparency = 1",
        "    else",
        "        visual:Destroy()",
        "        core.Transparency = 0",
        "    end",
        "end",
        "",
        "function UnitFactoryService.CreateCorePart(size, color, position, parent)",
        "    local p = Instance.new(""Part"")",
        "    p.Size = size",
        "    p.Color = color",
        "    p.Material = Enum.Material.Plastic",
        "    p.CanCollide = true",
        "    p.Anchored = false",
        "    p.Position = position",
        "    p.Parent = parent",
        "    return p",
        "end",
        "",
        "function UnitFactoryService.AttachMover(part, max_force, responsiveness, max_velocity)",
        "    local att = Instance.new(""Attachment"")",
        "    att.Parent = part",
        "",
        "    local ap = Instance.new(""AlignPosition"")",
        "    ap.Mode = Enum.PositionAlignmentMode.OneAttachment",
        "    ap.Attachment0 = att",
        "    ap.MaxForce = max_force",
        "    ap.Responsiveness = responsiveness",
        "    ap.MaxVelocity = max_velocity",
        "    ap.Parent = part",
        "",
        "    local ao = Instance.new(""AlignOrientation"")",
        "    ao.Mode = Enum.OrientationAlignmentMode.OneAttachment",
        "    ao.Attachment0 = att",
        "    ao.MaxTorque = max_force",
        "    ao.Responsiveness = responsiveness",
        "    ao.Parent = part",
        "",
        "    return ap",
        "end",
        "",
        "return UnitFactoryService"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "UnitFactoryService.lua") -Lines $unit_factory

    # -----------------------------
    # ArmyService.lua
    # -----------------------------
    $army_service = @(
        "local ArmyService = {}",
        "",
        "local RunService = game:GetService(""RunService"")",
        "",
        "local GameConfig = require(script.Parent.GameConfig)",
        "local UnitFactoryService = require(script.Parent.UnitFactoryService)",
        "",
        "local active_armies = {}",
        "local roaming_groups = {}",
        "",
        "local function now()",
        "    return os.clock()",
        "end",
        "",
        "local function dbg(fmt, ...)",
        "    if not GameConfig.Debug.Enabled then",
        "        return",
        "    end",
        "    print(string.format(""[ArmyService] "" .. fmt, ...))",
        "end",
        "",
        "local function compute_formation_pos(leader_pos, formation_index)",
        "    local golden = GameConfig.Formation.GoldenAngle",
        "    local inner_cap = GameConfig.Formation.InnerCapacity",
        "    local i = formation_index",
        "    if typeof(i) ~= ""number"" or i < 1 then",
        "        i = 1",
        "    end",
        "",
        "    local is_inner = (i <= inner_cap)",
        "    local local_i = i",
        "    local spacing = GameConfig.Formation.OuterSpacing",
        "    local radius_boost = 0",
        "",
        "    if is_inner then",
        "        spacing = GameConfig.Formation.InnerSpacing",
        "    else",
        "        local_i = i - inner_cap",
        "        spacing = GameConfig.Formation.OuterSpacing",
        "        radius_boost = GameConfig.Formation.OuterRadiusBoost",
        "    end",
        "",
        "    local r = (spacing * math.sqrt(local_i)) + radius_boost",
        "    local theta = local_i * golden",
        "",
        "    return Vector3.new(",
        "        leader_pos.X + r * math.cos(theta),",
        "        leader_pos.Y,",
        "        leader_pos.Z + r * math.sin(theta)",
        "    )",
        "end",
        "",
        "local function power_of_part(part)",
        "    local hp = part:GetAttribute(""HP"")",
        "    local dmg = part:GetAttribute(""Damage"")",
        "    if typeof(hp) ~= ""number"" then",
        "        hp = 0",
        "    end",
        "    if typeof(dmg) ~= ""number"" then",
        "        dmg = 0",
        "    end",
        "    return hp + (dmg * 12)",
        "end",
        "",
        "function ArmyService.Start(world_units, world_leaders)",
        "    ArmyService._units = world_units",
        "    ArmyService._leaders = world_leaders",
        "    dbg(""Ready."")",
        "",
        "    RunService.Heartbeat:Connect(function()",
        "        for _, army in pairs(active_armies) do",
        "            ArmyService.UpdateArmyFormation(army)",
        "        end",
        "    end)",
        "end",
        "",
        "function ArmyService.GetArmy(owner_id)",
        "    return active_armies[owner_id]",
        "end",
        "",
        "function ArmyService.GetAllArmies()",
        "    return active_armies",
        "end",
        "",
        "function ArmyService.GetRoamingGroups()",
        "    return roaming_groups",
        "end",
        "",
        "function ArmyService.CreatePlayerArmy(player, leader_part)",
        "    local owner_id = player.UserId",
        "    local army = active_armies[owner_id]",
        "    if not army then",
        "        army = { OwnerId = owner_id, Kind = ""Player"", Units = {}, NextIndex = 1 }",
        "        active_armies[owner_id] = army",
        "    end",
        "",
        "    army.Leader = leader_part",
        "    leader_part:SetAttribute(""OwnerId"", owner_id)",
        "    leader_part:SetAttribute(""Kind"", ""Leader"")",
        "    leader_part:SetAttribute(""LeaderKind"", ""Player"")",
        "    leader_part:SetAttribute(""DisplayName"", player.Name)",
        "    leader_part:SetAttribute(""HP"", GameConfig.Player.BaseHealth)",
        "    leader_part:SetAttribute(""MaxHP"", GameConfig.Player.BaseHealth)",
        "    leader_part:SetAttribute(""Damage"", GameConfig.Player.BaseDamage)",
        "",
        "    dbg(""Spawned player army: Player_%s (id=%s)"", player.Name, tostring(owner_id))",
        "",
        "    ArmyService.ClearUnits(owner_id)",
        "    for _ = 1, GameConfig.Player.StartCount do",
        "        ArmyService.AddUnit(owner_id, GameConfig.Player.StartType, ""Player"")",
        "    end",
        "end",
        "",
        "function ArmyService.CreateNamedArmy(def, leader_pos)",
        "    local owner_id = ""NAMED_"" .. tostring(math.floor(now() * 1000))",
        "",
        "    local leader = UnitFactoryService.CreateCorePart(",
        "        Vector3.new(6, 6, 6),",
        "        GameConfig.Colors.NamedLeader,",
        "        leader_pos,",
        "        ArmyService._leaders",
        "    )",
        "",
        "    leader.Name = def.Name",
        "    leader:SetAttribute(""OwnerId"", owner_id)",
        "    leader:SetAttribute(""Kind"", ""Leader"")",
        "    leader:SetAttribute(""LeaderKind"", ""NamedNPC"")",
        "    leader:SetAttribute(""IsNamedNPC"", true)",
        "    leader:SetAttribute(""DisplayName"", def.Name)",
        "    leader:SetAttribute(""HP"", 900)",
        "    leader:SetAttribute(""MaxHP"", 900)",
        "    leader:SetAttribute(""Damage"", 30)",
        "",
        "    UnitFactoryService.ApplyVisual(leader, def.Name)",
        "    UnitFactoryService.AttachMover(",
        "        leader,",
        "        GameConfig.Movement.LeaderMaxForce,",
        "        GameConfig.Movement.LeaderResponsiveness,",
        "        GameConfig.Movement.LeaderMaxVelocity",
        "    )",
        "",
        "    local army = {",
        "        OwnerId = owner_id,",
        "        Kind = ""Named"",",
        "        Name = def.Name,",
        "        Leader = leader,",
        "        Units = {},",
        "        NextIndex = 1,",
        "        ExpiresAt = now() + GameConfig.Spawn.NamedExpirySeconds,",
        "    }",
        "    active_armies[owner_id] = army",
        "",
        "    for _, entry in ipairs(def.Army) do",
        "        for _ = 1, entry.Count do",
        "            ArmyService.AddUnit(owner_id, entry.Type, ""Named"")",
        "        end",
        "    end",
        "",
        "    dbg(""Spawned named NPC army: %s (id=%s) expires=%ds"", def.Name, owner_id, GameConfig.Spawn.NamedExpirySeconds)",
        "    return army",
        "end",
        "",
        "function ArmyService.CreateWanderingGroup(unit_types, center_pos)",
        "    local group_id = ""G"" .. tostring(math.floor(now() * 1000))",
        "    local owner_id = ""WANDER_"" .. group_id",
        "",
        "    local group = {",
        "        GroupId = group_id,",
        "        OwnerId = owner_id,",
        "        Kind = ""Wander"",",
        "        Units = {},",
        "        Target = center_pos,",
        "        NextTargetAt = 0,",
        "        ExpiresAt = now() + GameConfig.Spawn.GroupExpirySeconds,",
        "    }",
        "    roaming_groups[group_id] = group",
        "",
        "    local radius = 7",
        "    for i, unit_type in ipairs(unit_types) do",
        "        local angle = (i / #unit_types) * math.pi * 2",
        "        local offset = Vector3.new(math.cos(angle) * radius, 0, math.sin(angle) * radius)",
        "        local spawn_pos = center_pos + offset",
        "",
        "        local part = ArmyService._spawn_unit_core(owner_id, unit_type, spawn_pos, ""Wander"")",
        "        local mover = UnitFactoryService.AttachMover(",
        "            part,",
        "            GameConfig.Movement.LeaderMaxForce,",
        "            GameConfig.Movement.LeaderResponsiveness,",
        "            GameConfig.Movement.LeaderMaxVelocity",
        "        )",
        "",
        "        table.insert(group.Units, { Part = part, Mover = mover, Offset = offset })",
        "    end",
        "",
        "    dbg(""Spawned wandering group: id=%s size=%d expires=%ds"", group_id, #unit_types, GameConfig.Spawn.GroupExpirySeconds)",
        "    return group",
        "end",
        "",
        "function ArmyService.ClearUnits(owner_id)",
        "    local army = active_armies[owner_id]",
        "    if not army then",
        "        return",
        "    end",
        "    for _, u in ipairs(army.Units) do",
        "        if u.Part and u.Part.Parent then",
        "            u.Part:Destroy()",
        "        end",
        "    end",
        "    army.Units = {}",
        "    army.NextIndex = 1",
        "end",
        "",
        "function ArmyService._spawn_unit_core(owner_id, unit_type, pos, faction)",
        "    local stats = GameConfig.Units[unit_type] or GameConfig.Units.Skeleton",
        "    local color = GameConfig.Colors.WanderUnit",
        "    if faction == ""Player"" then",
        "        color = GameConfig.Colors.PlayerUnit",
        "    elseif faction == ""Named"" then",
        "        color = GameConfig.Colors.NamedUnit",
        "    end",
        "",
        "    local unit = UnitFactoryService.CreateCorePart(",
        "        Vector3.new(stats.Size, stats.Size, stats.Size),",
        "        color,",
        "        pos + Vector3.new(0, 6, 0),",
        "        ArmyService._units",
        "    )",
        "",
        "    unit.Name = unit_type",
        "    unit:SetAttribute(""OwnerId"", owner_id)",
        "    unit:SetAttribute(""Kind"", ""Unit"")",
        "    unit:SetAttribute(""Type"", unit_type)",
        "    unit:SetAttribute(""DisplayName"", unit_type)",
        "    unit:SetAttribute(""HP"", stats.Health)",
        "    unit:SetAttribute(""MaxHP"", stats.Health)",
        "    unit:SetAttribute(""Damage"", stats.Damage)",
        "",
        "    UnitFactoryService.ApplyVisual(unit, unit_type)",
        "    return unit",
        "end",
        "",
        "function ArmyService.AddUnit(owner_id, unit_type, faction)",
        "    local army = active_armies[owner_id]",
        "    if not army or not army.Leader or not army.Leader.Parent then",
        "        return nil",
        "    end",
        "",
        "    local unit = ArmyService._spawn_unit_core(owner_id, unit_type, army.Leader.Position, faction)",
        "",
        "    local stats = GameConfig.Units[unit_type] or GameConfig.Units.Skeleton",
        "    local mover = UnitFactoryService.AttachMover(",
        "        unit,",
        "        GameConfig.Movement.UnitMaxForce * stats.Mass,",
        "        GameConfig.Movement.UnitResponsiveness,",
        "        GameConfig.Movement.UnitMaxVelocity",
        "    )",
        "",
        "    local idx = army.NextIndex or 1",
        "    army.NextIndex = idx + 1",
        "    unit:SetAttribute(""FormationIndex"", idx)",
        "",
        "    table.insert(army.Units, { Part = unit, Mover = mover })",
        "    return unit",
        "end",
        "",
        "function ArmyService.UpdateArmyFormation(army)",
        "    if not army.Leader or not army.Leader.Parent then",
        "        return",
        "    end",
        "",
        "    local center = army.Leader.Position",
        "    for _, u in ipairs(army.Units) do",
        "        if u.Part and u.Part.Parent then",
        "            local idx = u.Part:GetAttribute(""FormationIndex"") or 1",
        "            local target = compute_formation_pos(center, idx)",
        "            u.Mover.Position = target",
        "        end",
        "    end",
        "end",
        "",
        "function ArmyService.RemoveExpired()",
        "    local t = now()",
        "    for owner_id, army in pairs(active_armies) do",
        "        if army.Kind ~= ""Player"" and army.ExpiresAt and t >= army.ExpiresAt then",
        "            if army.Leader and army.Leader.Parent then",
        "                army.Leader:Destroy()",
        "            end",
        "            ArmyService.ClearUnits(owner_id)",
        "            active_armies[owner_id] = nil",
        "            dbg(""Removed expired army: id=%s"", tostring(owner_id))",
        "        end",
        "    end",
        "",
        "    for group_id, group in pairs(roaming_groups) do",
        "        if group.ExpiresAt and t >= group.ExpiresAt then",
        "            for _, u in ipairs(group.Units) do",
        "                if u.Part and u.Part.Parent then",
        "                    u.Part:Destroy()",
        "                end",
        "            end",
        "            roaming_groups[group_id] = nil",
        "            dbg(""Removed expired wandering group: id=%s"", tostring(group_id))",
        "        end",
        "    end",
        "end",
        "",
        "function ArmyService.PowerOfArmy(owner_id)",
        "    local army = active_armies[owner_id]",
        "    if not army then",
        "        return 0",
        "    end",
        "    local total = 0",
        "    if army.Leader and army.Leader.Parent then",
        "        total += power_of_part(army.Leader)",
        "    end",
        "    for _, u in ipairs(army.Units) do",
        "        if u.Part and u.Part.Parent then",
        "            total += power_of_part(u.Part)",
        "        end",
        "    end",
        "    return total",
        "end",
        "",
        "function ArmyService.PowerOfWanderingGroup(group_id)",
        "    local g = roaming_groups[group_id]",
        "    if not g then",
        "        return 0",
        "    end",
        "    local total = 0",
        "    for _, u in ipairs(g.Units) do",
        "        if u.Part and u.Part.Parent then",
        "            total += power_of_part(u.Part)",
        "        end",
        "    end",
        "    return total",
        "end",
        "",
        "return ArmyService"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "ArmyService.lua") -Lines $army_service

    # -----------------------------
    # SpawnService.lua
    # -----------------------------
    $spawn_service = @(
        "local SpawnService = {}",
        "",
        "local GameConfig = require(script.Parent.GameConfig)",
        "local BoundaryService = require(script.Parent.BoundaryService)",
        "local ArmyService = require(script.Parent.ArmyService)",
        "",
        "local last_tick = 0",
        "",
        "local function now()",
        "    return os.clock()",
        "end",
        "",
        "local function dbg(fmt, ...)",
        "    if not GameConfig.Debug.Enabled then",
        "        return",
        "    end",
        "    print(string.format(""[SpawnService] "" .. fmt, ...))",
        "end",
        "",
        "local function rand_range(a, b)",
        "    return a + (b - a) * math.random()",
        "end",
        "",
        "local function random_arena_pos()",
        "    local c = GameConfig.Arena.Center",
        "    local h = GameConfig.Arena.HalfSize",
        "    local x = rand_range(c.X - h.X, c.X + h.X)",
        "    local z = rand_range(c.Z - h.Z, c.Z + h.Z)",
        "    return Vector3.new(x, GameConfig.Arena.GroundY, z)",
        "end",
        "",
        "local function choose_wandering_composition()",
        "    local list = GameConfig.WanderingCompositions",
        "    local chosen = list[math.random(1, #list)]",
        "",
        "    -- Rarity: larger groups become rarer (simple reroll rule)",
        "    local size = #chosen",
        "    if size > 3 then",
        "        local roll = math.random()",
        "        local threshold = 0.55 - (size * 0.03)",
        "        if roll > threshold then",
        "            chosen = list[math.random(1, math.min(4, #list))]",
        "        end",
        "    end",
        "",
        "    local capped = {}",
        "    for i = 1, math.min(#chosen, GameConfig.Spawn.WanderingGroupMaxSize) do",
        "        table.insert(capped, chosen[i])",
        "    end",
        "    return capped",
        "end",
        "",
        "local function choose_named_def()",
        "    local list = GameConfig.NamedNPCs",
        "    return list[math.random(1, #list)]",
        "end",
        "",
        "local function count_named()",
        "    local c = 0",
        "    for _, a in pairs(ArmyService.GetAllArmies()) do",
        "        if a.Kind == ""Named"" then",
        "            c += 1",
        "        end",
        "    end",
        "    return c",
        "end",
        "",
        "local function count_wandering()",
        "    local c = 0",
        "    for _, _ in pairs(ArmyService.GetRoamingGroups()) do",
        "        c += 1",
        "    end",
        "    return c",
        "end",
        "",
        "function SpawnService.Start()",
        "    dbg(""Ready."")",
        "    task.spawn(function()",
        "        while true do",
        "            SpawnService.Tick()",
        "            task.wait(GameConfig.Debug.SpawnEverySeconds)",
        "        end",
        "    end)",
        "end",
        "",
        "function SpawnService.Tick()",
        "    ArmyService.RemoveExpired()",
        "",
        "    local named = count_named()",
        "    local wander = count_wandering()",
        "",
        "    dbg(""Tick: named=%d/%d wander=%d/%d"",",
        "        named, GameConfig.Spawn.MaxNamedArmies,",
        "        wander, GameConfig.Spawn.MaxWanderingGroups",
        "    )",
        "",
        "    if named < GameConfig.Spawn.MaxNamedArmies then",
        "        local roll = math.random()",
        "        if roll < GameConfig.Spawn.NamedSpawnChance then",
        "            dbg(""Spawn attempt: NAMED (roll=%.2f < %.2f)"", roll, GameConfig.Spawn.NamedSpawnChance)",
        "            local def = choose_named_def()",
        "            local pos = random_arena_pos()",
        "            ArmyService.CreateNamedArmy(def, pos)",
        "        end",
        "    end",
        "",
        "    if wander < GameConfig.Spawn.MaxWanderingGroups then",
        "        local roll = math.random()",
        "        if roll < GameConfig.Spawn.WanderingSpawnChance then",
        "            dbg(""Spawn attempt: WANDER (roll=%.2f < %.2f)"", roll, GameConfig.Spawn.WanderingSpawnChance)",
        "            local composition = choose_wandering_composition()",
        "            local pos = random_arena_pos()",
        "            ArmyService.CreateWanderingGroup(composition, pos)",
        "        end",
        "    end",
        "end",
        "",
        "return SpawnService"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "SpawnService.lua") -Lines $spawn_service

    # -----------------------------
    # AIStrategyService.lua
    # -----------------------------
    $ai_service = @(
        "local AIStrategyService = {}",
        "",
        "local GameConfig = require(script.Parent.GameConfig)",
        "local BoundaryService = require(script.Parent.BoundaryService)",
        "local ArmyService = require(script.Parent.ArmyService)",
        "",
        "local function now()",
        "    return os.clock()",
        "end",
        "",
        "local last_dbg = 0",
        "local function dbg(fmt, ...)",
        "    if not GameConfig.Debug.Enabled then",
        "        return",
        "    end",
        "    local t = now()",
        "    if (t - last_dbg) < GameConfig.Debug.AiEverySeconds then",
        "        return",
        "    end",
        "    last_dbg = t",
        "    print(string.format(""[AIStrategyService] "" .. fmt, ...))",
        "end",
        "",
        "local function rand_range(a, b)",
        "    return a + (b - a) * math.random()",
        "end",
        "",
        "local function pick_wander_target(pos)",
        "    local j = GameConfig.AI.WanderJitterStuds",
        "    local jitter = Vector3.new(rand_range(-j, j), 0, rand_range(-j, j))",
        "    return BoundaryService.ClampToArena(GameConfig, pos + jitter)",
        "end",
        "",
        "local function compute_center_of_group(group)",
        "    local sum = Vector3.new(0, 0, 0)",
        "    local count = 0",
        "    for _, u in ipairs(group.Units) do",
        "        if u.Part and u.Part.Parent then",
        "            sum += u.Part.Position",
        "            count += 1",
        "        end",
        "    end",
        "    if count <= 0 then",
        "        return nil",
        "    end",
        "    local c = sum / count",
        "    return Vector3.new(c.X, GameConfig.Arena.GroundY, c.Z)",
        "end",
        "",
        "local function group_power(group)",
        "    return ArmyService.PowerOfWanderingGroup(group.GroupId)",
        "end",
        "",
        "local function army_center(army)",
        "    if army.Leader and army.Leader.Parent then",
        "        return Vector3.new(army.Leader.Position.X, GameConfig.Arena.GroundY, army.Leader.Position.Z)",
        "    end",
        "    return nil",
        "end",
        "",
        "local function find_nearest_enemy(self_owner, self_pos)",
        "    local best = nil",
        "    local best_dist = GameConfig.AI.SenseRange",
        "",
        "    for owner_id, army in pairs(ArmyService.GetAllArmies()) do",
        "        if owner_id ~= self_owner then",
        "            local pos = army_center(army)",
        "            if pos then",
        "                local d = (pos - self_pos).Magnitude",
        "                if d < best_dist then",
        "                    best_dist = d",
        "                    best = { Kind = ""Army"", OwnerId = owner_id, Pos = pos, Power = ArmyService.PowerOfArmy(owner_id) }",
        "                end",
        "            end",
        "        end",
        "    end",
        "",
        "    for group_id, group in pairs(ArmyService.GetRoamingGroups()) do",
        "        if group.OwnerId ~= self_owner then",
        "            local pos = compute_center_of_group(group)",
        "            if pos then",
        "                local d = (pos - self_pos).Magnitude",
        "                if d < best_dist then",
        "                    best_dist = d",
        "                    best = { Kind = ""Group"", OwnerId = group.OwnerId, Pos = pos, Power = group_power(group) }",
        "                end",
        "            end",
        "        end",
        "    end",
        "",
        "    return best, best_dist",
        "end",
        "",
        "local function chase_or_flee(self_pos, self_power, enemy)",
        "    local to_enemy = enemy.Pos - self_pos",
        "    local dist = to_enemy.Magnitude",
        "    if dist <= 0.01 then",
        "        return pick_wander_target(self_pos), ""Wander""",
        "    end",
        "",
        "    local stronger = self_power >= (enemy.Power * GameConfig.AI.Hysteresis)",
        "    if stronger then",
        "        if dist > GameConfig.AI.ChaseStopRange then",
        "            return BoundaryService.ClampToArena(GameConfig, enemy.Pos), ""Chase""",
        "        end",
        "        return BoundaryService.ClampToArena(GameConfig, self_pos), ""Hold""",
        "    end",
        "",
        "    local away = (-to_enemy).Unit",
        "    local flee_pos = self_pos + (away * GameConfig.AI.FleeDistance)",
        "    return BoundaryService.ClampToArena(GameConfig, flee_pos), ""Flee""",
        "end",
        "",
        "function AIStrategyService.Start()",
        "    dbg(""Ready."")",
        "    task.spawn(function()",
        "        while true do",
        "            AIStrategyService.Tick()",
        "            task.wait(0.18)",
        "        end",
        "    end)",
        "end",
        "",
        "function AIStrategyService.Tick()",
        "    local t = now()",
        "",
        "    -- Wandering groups",
        "    for group_id, group in pairs(ArmyService.GetRoamingGroups()) do",
        "        local center = compute_center_of_group(group)",
        "        if not center then",
        "            continue",
        "        end",
        "",
        "        if t >= (group.NextTargetAt or 0) then",
        "            local enemy = find_nearest_enemy(group.OwnerId, center)",
        "            local my_power = group_power(group)",
        "            if enemy then",
        "                local target, mode = chase_or_flee(center, my_power, enemy)",
        "                group.Target = target",
        "                dbg(""%s: %s -> %s (my=%d enemy=%d dist=%.1f)"",",
        "                    mode,",
        "                    ""Wanderers"",",
        "                    enemy.Kind,",
        "                    my_power,",
        "                    enemy.Power,",
        "                    (enemy.Pos - center).Magnitude",
        "                )",
        "            else",
        "                group.Target = pick_wander_target(center)",
        "                dbg(""Wander: id=%s newTarget=(%d,%d)"", group_id, group.Target.X, group.Target.Z)",
        "            end",
        "",
        "            group.NextTargetAt = t + rand_range(",
        "                GameConfig.Movement.TargetUpdateMinSeconds,",
        "                GameConfig.Movement.TargetUpdateMaxSeconds",
        "            )",
        "        end",
        "",
        "        if group.Target then",
        "            for _, u in ipairs(group.Units) do",
        "                if u.Part and u.Part.Parent then",
        "                    local desired = group.Target + (u.Offset or Vector3.new())",
        "                    u.Mover.Position = BoundaryService.ClampToArena(GameConfig, desired)",
        "                end",
        "            end",
        "        end",
        "    end",
        "",
        "    -- Named NPC leaders (leaders move; units are formation-driven by ArmyService)",
        "    for owner_id, army in pairs(ArmyService.GetAllArmies()) do",
        "        if army.Kind == ""Named"" and army.Leader and army.Leader.Parent then",
        "            local leader = army.Leader",
        "            local self_pos = Vector3.new(leader.Position.X, GameConfig.Arena.GroundY, leader.Position.Z)",
        "            local enemy = find_nearest_enemy(owner_id, self_pos)",
        "            local my_power = ArmyService.PowerOfArmy(owner_id)",
        "",
        "            local mover = leader:FindFirstChildWhichIsA(""AlignPosition"")",
        "            if mover then",
        "                if enemy then",
        "                    local target, mode = chase_or_flee(self_pos, my_power, enemy)",
        "                    mover.Position = target",
        "                    dbg(""%s: %s -> %s (my=%d enemy=%d dist=%.1f)"",",
        "                        mode,",
        "                        army.Name or ""Named"",",
        "                        enemy.Kind,",
        "                        my_power,",
        "                        enemy.Power,",
        "                        (enemy.Pos - self_pos).Magnitude",
        "                    )",
        "                else",
        "                    mover.Position = pick_wander_target(self_pos)",
        "                end",
        "            end",
        "        end",
        "    end",
        "end",
        "",
        "return AIStrategyService"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "AIStrategyService.lua") -Lines $ai_service

    # -----------------------------
    # CombatService.lua
    # -----------------------------
    $combat_service = @(
        "local CombatService = {}",
        "",
        "local GameConfig = require(script.Parent.GameConfig)",
        "local ArmyService = require(script.Parent.ArmyService)",
        "",
        "local function now()",
        "    return os.clock()",
        "end",
        "",
        "local last_dbg = 0",
        "local function dbg(fmt, ...)",
        "    if not GameConfig.Debug.Enabled then",
        "        return",
        "    end",
        "    local t = now()",
        "    if (t - last_dbg) < GameConfig.Debug.CombatEverySeconds then",
        "        return",
        "    end",
        "    last_dbg = t",
        "    print(string.format(""[CombatService] "" .. fmt, ...))",
        "end",
        "",
        "local function is_alive(part)",
        "    local hp = part:GetAttribute(""HP"")",
        "    return typeof(hp) == ""number"" and hp > 0",
        "end",
        "",
        "local function get_damage(part)",
        "    local dmg = part:GetAttribute(""Damage"")",
        "    if typeof(dmg) ~= ""number"" then",
        "        return 5",
        "    end",
        "    return dmg",
        "end",
        "",
        "local function power_of_part(part)",
        "    local hp = part:GetAttribute(""HP"")",
        "    local dmg = part:GetAttribute(""Damage"")",
        "    if typeof(hp) ~= ""number"" then",
        "        hp = 0",
        "    end",
        "    if typeof(dmg) ~= ""number"" then",
        "        dmg = 0",
        "    end",
        "    return hp + (dmg * 12)",
        "end",
        "",
        "local function should_raise()",
        "    return math.random() < GameConfig.Raising.BaseChance",
        "end",
        "",
        "local function can_raiser_raise(killer_owner)",
        "    local army = ArmyService.GetArmy(killer_owner)",
        "    if not army then",
        "        return false",
        "    end",
        "    return (army.Kind == ""Player"") or (army.Kind == ""Named"")",
        "end",
        "",
        "local function try_raise_unit(killer_owner, unit_type, guaranteed)",
        "    if not can_raiser_raise(killer_owner) then",
        "        return false",
        "    end",
        "    if guaranteed then",
        "        ArmyService.AddUnit(killer_owner, unit_type, (ArmyService.GetArmy(killer_owner).Kind == ""Player"") and ""Player"" or ""Named"")",
        "        return true",
        "    end",
        "    if should_raise() then",
        "        ArmyService.AddUnit(killer_owner, unit_type, (ArmyService.GetArmy(killer_owner).Kind == ""Player"") and ""Player"" or ""Named"")",
        "        return true",
        "    end",
        "    return false",
        "end",
        "",
        "local function destroy_part(part)",
        "    if part and part.Parent then",
        "        part:Destroy()",
        "    end",
        "end",
        "",
        "local function resolve_death(killer, victim)",
        "    local killer_owner = killer:GetAttribute(""OwnerId"")",
        "    local victim_owner = victim:GetAttribute(""OwnerId"")",
        "    local victim_type = victim:GetAttribute(""Type"") or victim.Name or ""Skeleton""",
        "",
        "    local victim_kind = victim:GetAttribute(""Kind"")",
        "    local victim_leader_kind = victim:GetAttribute(""LeaderKind"")",
        "",
        "    -- Named leader death: guaranteed boss raise for killer (if raiser)",
        "    if victim_kind == ""Leader"" and victim_leader_kind == ""NamedNPC"" then",
        "        if GameConfig.Raising.NamedLeaderKillGuaranteedBossRaise then",
        "            local ok = try_raise_unit(killer_owner, GameConfig.Raising.BossRaiseType, true)",
        "            dbg(""Named leader killed. Guaranteed boss raise=%s for killer=%s"", tostring(ok), tostring(killer_owner))",
        "        end",
        "        local army = ArmyService.GetArmy(victim_owner)",
        "        if army then",
        "            ArmyService.ClearUnits(victim_owner)",
        "            if army.Leader and army.Leader.Parent then",
        "                army.Leader:Destroy()",
        "            end",
        "            -- leave expiry cleanup to ArmyService.RemoveExpired; hard-remove now",
        "            ArmyService.GetAllArmies()[victim_owner] = nil",
        "        end",
        "        return",
        "    end",
        "",
        "    -- Wandering units do not get raised by wanderers (they cannot raise),",
        "    -- but can be raised by player/named killers.",
        "    local raised = false",
        "    if victim_kind == ""Unit"" then",
        "        raised = try_raise_unit(killer_owner, victim_type, false)",
        "    end",
        "",
        "    if raised then",
        "        dbg(""Raised unit: killer=%s type=%s"", tostring(killer_owner), tostring(victim_type))",
        "        destroy_part(victim)",
        "    else",
        "        destroy_part(victim)",
        "    end",
        "end",
        "",
        "local function apply_damage(attacker, target)",
        "    local dmg = get_damage(attacker)",
        "    local hp = target:GetAttribute(""HP"")",
        "    local max_hp = target:GetAttribute(""MaxHP"")",
        "    if typeof(hp) ~= ""number"" or typeof(max_hp) ~= ""number"" then",
        "        return",
        "    end",
        "    if hp <= 0 then",
        "        return",
        "    end",
        "",
        "    local new_hp = hp - dmg",
        "    target:SetAttribute(""HP"", new_hp)",
        "    if new_hp <= 0 then",
        "        resolve_death(attacker, target)",
        "    end",
        "end",
        "",
        "local function collect_combat_parts()",
        "    local list = {}",
        "    for _, army in pairs(ArmyService.GetAllArmies()) do",
        "        if army.Leader and army.Leader.Parent then",
        "            table.insert(list, army.Leader)",
        "        end",
        "        for _, u in ipairs(army.Units) do",
        "            if u.Part and u.Part.Parent then",
        "                table.insert(list, u.Part)",
        "            end",
        "        end",
        "    end",
        "    for _, group in pairs(ArmyService.GetRoamingGroups()) do",
        "        for _, u in ipairs(group.Units) do",
        "            if u.Part and u.Part.Parent then",
        "                table.insert(list, u.Part)",
        "            end",
        "        end",
        "    end",
        "    return list",
        "end",
        "",
        "function CombatService.Start()",
        "    dbg(""Ready."")",
        "    task.spawn(function()",
        "        while true do",
        "            CombatService.Tick()",
        "            task.wait(GameConfig.Combat.AttackCooldownSeconds)",
        "        end",
        "    end)",
        "end",
        "",
        "function CombatService.Tick()",
        "    local parts = collect_combat_parts()",
        "    if #parts <= 1 then",
        "        return",
        "    end",
        "",
        "    for i = 1, #parts do",
        "        local a = parts[i]",
        "        if a and a.Parent and is_alive(a) then",
        "            local owner_a = a:GetAttribute(""OwnerId"")",
        "            local best = nil",
        "            local best_d = GameConfig.Combat.AttackRange",
        "",
        "            for j = 1, #parts do",
        "                if j ~= i then",
        "                    local b = parts[j]",
        "                    if b and b.Parent and is_alive(b) then",
        "                        local owner_b = b:GetAttribute(""OwnerId"")",
        "                        if owner_b ~= nil and owner_a ~= nil and owner_b ~= owner_a then",
        "                            local d = (a.Position - b.Position).Magnitude",
        "                            if d < best_d then",
        "                                best_d = d",
        "                                best = b",
        "                            end",
        "                        end",
        "                    end",
        "                end",
        "            end",
        "",
        "            if best then",
        "                apply_damage(a, best)",
        "            end",
        "        end",
        "    end",
        "end",
        "",
        "return CombatService"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $services_dir "CombatService.lua") -Lines $combat_service

    # -----------------------------
    # Main.server.lua
    # -----------------------------
    $main_server = @(
        "local Players = game:GetService(""Players"")",
        "",
        "print(""[Server] Booting NecroSnake"")",
        "",
        "local GameConfig = require(script.Parent.Services.GameConfig)",
        "local WorldService = require(script.Parent.Services.WorldService)",
        "local BoundaryService = require(script.Parent.Services.BoundaryService)",
        "local ModelLibraryService = require(script.Parent.Services.ModelLibraryService)",
        "local ArmyService = require(script.Parent.Services.ArmyService)",
        "local SpawnService = require(script.Parent.Services.SpawnService)",
        "local AIStrategyService = require(script.Parent.Services.AIStrategyService)",
        "local CombatService = require(script.Parent.Services.CombatService)",
        "",
        "local world = WorldService.EnsureWorld(GameConfig)",
        "BoundaryService.BuildWalls(GameConfig, world.Arena)",
        "ModelLibraryService.Sanitize()",
        "",
        "ArmyService.Start(world.Units, world.Leaders)",
        "SpawnService.Start()",
        "AIStrategyService.Start()",
        "CombatService.Start()",
        "",
        "local function setup_player(player)",
        "    player.CharacterAdded:Connect(function(char)",
        "        local hrp = char:WaitForChild(""HumanoidRootPart"")",
        "        hrp:SetAttribute(""OwnerId"", player.UserId)",
        "        hrp:SetAttribute(""Kind"", ""Leader"")",
        "        hrp:SetAttribute(""LeaderKind"", ""Player"")",
        "        hrp:SetAttribute(""DisplayName"", player.Name)",
        "        hrp:SetAttribute(""HP"", GameConfig.Player.BaseHealth)",
        "        hrp:SetAttribute(""MaxHP"", GameConfig.Player.BaseHealth)",
        "        hrp:SetAttribute(""Damage"", GameConfig.Player.BaseDamage)",
        "",
        "        ArmyService.CreatePlayerArmy(player, hrp)",
        "    end)",
        "end",
        "",
        "Players.PlayerAdded:Connect(setup_player)",
        "for _, p in ipairs(Players:GetPlayers()) do",
        "    setup_player(p)",
        "end",
        "",
        "print(""[Server] NecroSnake boot complete"")"
    )
    Write-TextFileUtf8NoBom -Path (Join-Path $server_root "Main.server.lua") -Lines $main_server

    # Convert all Lua to UTF-8 no BOM
    $converted = Convert-LuaTreeToUtf8NoBom -Root $src_root
    Write-Host "✅ Converted $converted .lua file(s) under src/ to UTF-8 (no BOM)."
    Write-Host ""
    Write-Host "✅ Rojo patch applied."
    Write-Host "Next:"
    Write-Host "1) Start Rojo:  cd `"$ProjectRoot`" ; & (Join-Path `$env:USERPROFILE `".aftman\bin\rojo.exe`") serve `".\default.project.json`""
    Write-Host "2) Studio: Plugins -> Rojo -> Connect -> Sync"
    Write-Host "3) Stop -> Play"
}

Main
